language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

matrix:
  include:
    - env: TEST_SUITE="adddelete"
    - env: TEST_SUITE="compartmentedmodel"
    - env: TEST_SUITE="fixed_recovery"
    - env: TEST_SUITE="networkdynamics"
    - env: TEST_SUITE="sir"
    - env: TEST_SUITE="sirs"
    - env: TEST_SUITE="sis"
    - env: TEST_SUITE="stochasticrates"

script:
  - python setup.py install
  - python test/test_${TEST_SUITE}.py
