language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install codecov

matrix:
  include:
    - env: TEST_SUITE="adddelete"
    - env: TEST_SUITE="compartmentedmodel"
    - env: TEST_SUITE="fixed_recovery"
    - env: TEST_SUITE="networkdynamics"
    - env: TEST_SUITE="sir"
    - env: TEST_SUITE="sirs"
    - env: TEST_SUITE="sis"
    - env: TEST_SUITE="seir"
    - env: TEST_SUITE="stochasticrates"
    - env: TEST_SUITE="monitor"

script:
  - python setup.py install
  - coverage run -m nose test/test_${TEST_SUITE}.py

after_success:
  - coveralls
